### ISSUE TITLE
error: Error: While resolving module `@root/client/providers/AppProvider`, the Haste package `@root/client` was found. However the module `providers/AppProvider` could not be found within the package. Indeed, none of these files exist:

### ISSUE THREAD

**Issue by adonyssantos** [adonyssantos/gentleman-community-twitter-clone#56]
### Error with the **mobile app**.

```bash
error: Error: While resolving module `@root/client/providers/AppProvider`, the Haste package `@root/client` was found. However the module `providers/AppProvider` could not be found within the package. Indeed, none of these files exist:

  * `/home/adonys/Development/gentleman-community-twitter-clone/packages/client/providers/AppProvider(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)`
  * `/home/adonys/Development/gentleman-community-twitter-clone/packages/client/providers/AppProvider/index(.native|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json)`
    at resolveHasteName (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro-resolver/src/resolve.js:173:9)
    at Object.resolve (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro-resolver/src/resolve.js:63:20)
    at ModuleResolver.resolveDependency (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:111:31)
    at DependencyGraph.resolveDependency (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (/home/adonys/Development/gentleman-community-twitter-clone/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 2)
iOS Bundling failed 19ms
```

**Comment by adonyssantos** [comment]
https://stackoverflow.com/questions/53818240/how-to-use-babel-module-resolver-with-react-nativeexpo-on-publication
